#!/usr/bin/env bash
# Sesame — generate .env from vault for the current project

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/vault.sh"
source "${SCRIPT_DIR}/output.sh"

# Generate a .env file for the current project from vault data.
# Usage: sesame_inject [target_dir]
sesame_inject() {
  local target_dir="${1:-.}"
  local env_file="${target_dir}/.env"
  local project
  project="$(project_current)"

  vault_init

  local key_ids
  key_ids=$(vault_list_project "$project")

  if [[ -z "$key_ids" ]]; then
    sesame_warn "No keys linked to project '${project}' in vault."
    sesame_info "Run /sesame <service> to provision keys first."
    return 1
  fi

  # Build .env content
  local env_content=""
  while IFS= read -r key_id; do
    [[ -z "$key_id" ]] && continue
    local service mode
    service=$(vault_get_field "$key_id" "service")
    mode=$(vault_get_field "$key_id" "mode")

    case "$service" in
      stripe)
        local sk pk
        sk=$(vault_get_field "$key_id" "secret_key")
        pk=$(vault_get_field "$key_id" "publishable_key")
        if [[ -n "$sk" ]]; then
          env_content+="STRIPE_SECRET_KEY=${sk}"$'\n'
        fi
        if [[ -n "$pk" ]]; then
          env_content+="STRIPE_PUBLISHABLE_KEY=${pk}"$'\n'
        fi
        ;;
      supabase)
        local url anon_key service_role_key
        url=$(vault_get_field "$key_id" "url")
        anon_key=$(vault_get_field "$key_id" "anon_key")
        service_role_key=$(vault_get_field "$key_id" "service_role_key")
        [[ -n "$url" ]] && env_content+="SUPABASE_URL=${url}"$'\n'
        [[ -n "$anon_key" ]] && env_content+="SUPABASE_ANON_KEY=${anon_key}"$'\n'
        [[ -n "$service_role_key" ]] && env_content+="SUPABASE_SERVICE_ROLE_KEY=${service_role_key}"$'\n'
        ;;
      vercel)
        local token project_id org_id
        token=$(vault_get_field "$key_id" "token")
        project_id=$(vault_get_field "$key_id" "project_id")
        org_id=$(vault_get_field "$key_id" "org_id")
        [[ -n "$token" ]] && env_content+="VERCEL_TOKEN=${token}"$'\n'
        [[ -n "$project_id" ]] && env_content+="VERCEL_PROJECT_ID=${project_id}"$'\n'
        [[ -n "$org_id" ]] && env_content+="VERCEL_ORG_ID=${org_id}"$'\n'
        ;;
      *)
        # Generic: export all non-metadata fields
        local fields
        fields=$(vault_get_key "$key_id" | jq -r 'del(.service, .mode, .created, .used_by) | to_entries[] | "\(.key)=\(.value)"')
        if [[ -n "$fields" ]]; then
          env_content+="${fields}"$'\n'
        fi
        ;;
    esac
  done <<< "$key_ids"

  if [[ -z "$env_content" ]]; then
    sesame_warn "Keys found but no env vars to inject."
    return 1
  fi

  # Write .env
  echo "# Generated by Sesame — do not edit manually" > "$env_file"
  echo "# Project: ${project}" >> "$env_file"
  echo "# Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$env_file"
  echo "" >> "$env_file"
  echo -n "$env_content" >> "$env_file"
  chmod 600 "$env_file"

  # Ensure .env is in .gitignore
  _ensure_gitignore "$target_dir"

  sesame_ok "Wrote ${env_file} with $(echo "$env_content" | grep -c '=') variables"
}

# Ensure .env is in .gitignore
_ensure_gitignore() {
  local target_dir="${1:-.}"
  local gitignore="${target_dir}/.gitignore"
  if [[ -f "$gitignore" ]]; then
    if ! grep -qx '\.env' "$gitignore" 2>/dev/null; then
      echo '.env' >> "$gitignore"
      sesame_info "Added .env to .gitignore"
    fi
  else
    echo '.env' > "$gitignore"
    sesame_info "Created .gitignore with .env"
  fi
}
